Conditions:
  CloudWatchLoggingIsEnabled:
    Fn::And:
    - {Condition: CloudWatchLogsRoleArnIsDefined}
    - {Condition: CloudWatchLogsLogGroupArnIsDefined}
  CloudWatchLogsLogGroupArnIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - {Ref: CloudWatchLogsLogGroupArn}
  CloudWatchLogsRoleArnIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - {Ref: CloudWatchLogsRoleArn}
  KMSKeyIdIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - {Ref: KMSKeyId}
  S3KeyPrefixIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - {Ref: S3KeyPrefix}
  SnsTopicNameIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - {Ref: SnsTopicName}
Description: CloudTrail Trail
Outputs:
  CloudTrail:
    Description: CloudTrail
    Value: {Ref: CloudTrail}
Parameters:
  CloudWatchLogsLogGroupArn: {Default: '', Description: Role that CloudWatch Logs
      assumes to write logs to a log group, Type: String}
  CloudWatchLogsRoleArn: {Default: '', Description: Log group to which CloudTrail
      logs will be delivered, Type: String}
  EnableLogFileValidation: {Default: 'false', Description: Whether CloudTrail validates
      the integrity of log files, Type: String}
  IncludeGlobalServiceEvents: {Default: 'true', Description: 'Whether to publish events
      from global services, such as IAM', Type: String}
  IsLogging: {Default: 'true', Description: Whether to log AWS API calls, Type: String}
  IsMultiRegionTrail: {Default: 'true', Description: Whether the trail is created
      in all regions, Type: String}
  KMSKeyId: {Default: '', Description: KMS key ID to use to encrypt CloudTrail logs,
    Type: String}
  S3BucketName: {Description: Name of the Amazon S3 bucket where CloudTrail publishes
      log files, Type: String}
  S3KeyPrefix: {Default: '', Description: Amazon S3 object key prefix that precedes
      the name of all log files, Type: String}
  SnsTopicName: {Default: '', Description: SNS topic that is notified when new log
      files are published, Type: String}
Resources:
  CloudTrail:
    Properties:
      CloudWatchLogsLogGroupArn:
        Fn::If:
        - CloudWatchLoggingIsEnabled
        - {Ref: CloudWatchLogsLogGroupArn}
        - {Ref: 'AWS::NoValue'}
      CloudWatchLogsRoleArn:
        Fn::If:
        - CloudWatchLoggingIsEnabled
        - {Ref: CloudWatchLogsRoleArn}
        - {Ref: 'AWS::NoValue'}
      EnableLogFileValidation: {Ref: EnableLogFileValidation}
      IncludeGlobalServiceEvents: {Ref: IncludeGlobalServiceEvents}
      IsLogging: {Ref: IsLogging}
      IsMultiRegionTrail: {Ref: IsMultiRegionTrail}
      KMSKeyId:
        Fn::If:
        - KMSKeyIdIsDefined
        - {Ref: KMSKeyId}
        - {Ref: 'AWS::NoValue'}
      S3BucketName: {Ref: S3BucketName}
      S3KeyPrefix:
        Fn::If:
        - S3KeyPrefixIsDefined
        - {Ref: S3KeyPrefix}
        - {Ref: 'AWS::NoValue'}
      SnsTopicName:
        Fn::If:
        - SnsTopicNameIsDefined
        - {Ref: SnsTopicName}
        - {Ref: 'AWS::NoValue'}
      Tags:
      - {Key: Division, Value: N/A}
      - {Key: Owner, Value: Jetstar}
      - {Key: Environment, Value: production}
      - {Key: Name, Value: CloudTrail}
    Type: AWS::CloudTrail::Trail
