Conditions:
  CrossAccountTrustedPrincipalsIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Fn::Join:
        - ''
        - {Ref: CrossAccountTrustedPrincipals}
  ManagedPolicyArnslsIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Fn::Join:
        - ''
        - {Ref: ManagedPolicyArns}
  RoleNameIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - {Ref: RoleName}
  RolePathIsDefined:
    Fn::Not:
    - Fn::Equals:
      - ''
      - {Ref: RolePath}
Description: IAM Role
Outputs:
  RoleARN:
    Value:
      Fn::GetAtt: [IAMRole, Arn]
  RoleName:
    Value: {Ref: IAMRole}
Parameters:
  CrossAccountTrustedPrincipals: {Default: '', Description: Additional principals
      to allow assumption of the role, Type: CommaDelimitedList}
  ManagedPolicyArns: {Default: '', Description: Managed policy ARNs to attach to this
      role, Type: CommaDelimitedList}
  RoleName: {Default: '', Description: IAM role name, Type: String}
  RolePath: {Default: '', Description: The path associated with this IAM role, Type: String}
Resources:
  IAMRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Fn::If:
            - CrossAccountTrustedPrincipalsIsDefined
            - AWS: {Ref: CrossAccountTrustedPrincipals}
              Service: cloudtrail.amazonaws.com
            - {Service: cloudtrail.amazonaws.com}
        Version: '2012-10-17'
      ManagedPolicyArns:
        Fn::If:
        - ManagedPolicyArnslsIsDefined
        - {Ref: ManagedPolicyArns}
        - {Ref: 'AWS::NoValue'}
      Path:
        Fn::If:
        - RolePathIsDefined
        - {Ref: RolePath}
        - {Ref: 'AWS::NoValue'}
      Policies:
      - PolicyDocument:
          Statement:
          - Action: ['logs:CreateLogStream', 'logs:PutLogEvents']
            Effect: Allow
            Resource: ['arn:aws:logs:ap-southeast-2:948174138596:log-group:cloudtrail-logs:log-stream:*']
          Version: '2012-10-17'
        PolicyName: CloudTrail-CloudWatch-log-policy
      RoleName:
        Fn::If:
        - RoleNameIsDefined
        - {Ref: RoleName}
        - {Ref: 'AWS::NoValue'}
    Type: AWS::IAM::Role
